// Code generated by tools/gen_tags. DO NOT EDIT.
// Regenerate with: go run tools/gen_tags/main.go > internal/analyzer/rules_gen.go

package analyzer

import "github.com/vikranthBala/esi-lsp/internal/parser"

var TagRules = map[parser.NodeKind]TagMeta{
	"esi:assign": {
		requiredAttrs: []string{"name", "value"},
		allowedAttrs:  []string{"name", "value"},
		summary:       "Assigns a value to a user-defined variable",
		attrDocs: map[string]string{
			"name":  "Variable name to assign to",
			"value": "Value to assign",
		},
	},
	"esi:attempt": {
		requiredAttrs: []string{},
		allowedAttrs:  []string{},
		summary:       "Primary branch within esi:try, content to attempt first",
		attrDocs:      map[string]string{},
	},
	"esi:choose": {
		requiredAttrs: []string{},
		allowedAttrs:  []string{},
		summary:       "Conditional resource selection",
		attrDocs:      map[string]string{},
	},
	"esi:comment": {
		requiredAttrs: []string{},
		allowedAttrs:  []string{"text"},
		summary:       "Adds commentary within ESI blocks",
		attrDocs: map[string]string{
			"text": "Comment text",
		},
	},
	"esi:eval": {
		requiredAttrs: []string{},
		allowedAttrs:  []string{"src", "maxwait"},
		summary:       "Evaluates another ESI page inline at processing time",
		attrDocs: map[string]string{
			"src":     "URL of the ESI page to evaluate",
			"maxwait": "Timeout in milliseconds",
		},
	},
	"esi:except": {
		requiredAttrs: []string{},
		allowedAttrs:  []string{},
		summary:       "Execute alternative content if ESI attempt fails",
		attrDocs:      map[string]string{},
	},
	"esi:function": {
		requiredAttrs: []string{"return"},
		allowedAttrs:  []string{"return"},
		summary:       "Function block for returning values",
		attrDocs: map[string]string{
			"return": "Value to be returned",
		},
	},
	"esi:include": {
		requiredAttrs: []string{"src"},
		allowedAttrs:  []string{"alt", "dcab", "onerror", "maxwait", "ttl"},
		summary:       "Statement to include external objects",
		attrDocs: map[string]string{
			"src":     "primary object to fetch",
			"alt":     "object to fetch if src not found",
			"dcab":    "type of processing for object",
			"onerror": "ignores failed fetches and continues serving the page",
			"maxwait": "time-out period for EdgeSuite to wait for fetch",
			"ttl":     "caching duration",
		},
	},
	"esi:inline": {
		requiredAttrs: []string{"name", "fetchable"},
		allowedAttrs:  []string{"name", "fetchable"},
		summary:       "Defines an inline ESI fragment that can be included by name",
		attrDocs: map[string]string{
			"name":      "Name of the inline fragment",
			"fetchable": "Whether the fragment can be fetched independently",
		},
	},
	"esi:otherwise": {
		requiredAttrs: []string{},
		allowedAttrs:  []string{},
		summary:       "Evaluates content if all when conditions are false",
		attrDocs:      map[string]string{},
	},
	"esi:remove": {
		requiredAttrs: []string{},
		allowedAttrs:  []string{},
		summary:       "Removes content block at ESI processing time",
		attrDocs:      map[string]string{},
	},
	"esi:text": {
		requiredAttrs: []string{},
		allowedAttrs:  []string{"src"},
		summary:       "Inserts flat text without ESI processing",
		attrDocs: map[string]string{
			"src": "URL of the fragment",
		},
	},
	"esi:try": {
		requiredAttrs: []string{},
		allowedAttrs:  []string{},
		summary:       "Error handling container, wraps esi:attempt and esi:except",
		attrDocs:      map[string]string{},
	},
	"esi:vars": {
		requiredAttrs: []string{},
		allowedAttrs:  []string{"cid", "alt"},
		summary:       "Define and evaluate variables within a fragment",
		attrDocs: map[string]string{
			"cid": "EdgeSuite identifier",
			"alt": "Specify alternative object if src object cannot be fetched",
		},
	},
	"esi:when": {
		requiredAttrs: []string{"test"},
		allowedAttrs:  []string{"test"},
		summary:       "Conditional content based on Boolean expression",
		attrDocs: map[string]string{
			"test": "Boolean expression",
		},
	},
}
