package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

type Tag struct {
	Tag           string            `json:"tag"`
	Summary       string            `json:"summary"`
	RequiredAttrs []string          `json:"requiredAttrs"`
	AllowedAttrs  []string          `json:"allowedAttrs"`
	AttrDocs      map[string]string `json:"attrDocs"`
}

func main() {
	data, err := os.ReadFile("tags.json")
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read tags.json: %v\n", err)
		os.Exit(1)
	}

	var tags map[string]Tag
	if err := json.Unmarshal(data, &tags); err != nil {
		fmt.Fprintf(os.Stderr, "failed to parse tags.json: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("// Code generated by tools/gen_tags. DO NOT EDIT.")
	fmt.Println("// Regenerate with: go run tools/gen_tags/main.go > internal/analyzer/rules_gen.go")
	fmt.Println()
	fmt.Println("package analyzer")
	fmt.Println()
	fmt.Println(`import "github.com/vikranthBala/esi-lsp/internal/parser"`)
	fmt.Println()

	fmt.Println("var TagRules = map[parser.NodeKind]TagMeta{")

	keys := make([]string, 0, len(tags))
	for k := range tags {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		v := tags[k]
		fmt.Printf("\t%q: {\n", k)

		fmt.Printf("\t\tRequiredAttrs: %#v,\n", v.RequiredAttrs)
		fmt.Printf("\t\tAllowedAttrs: %#v,\n", v.AllowedAttrs)
		fmt.Printf("\t\tSummary: %q,\n", v.Summary)

		fmt.Println("\t\tAttrDocs: map[string]string{")
		for ak, av := range v.AttrDocs {
			fmt.Printf("\t\t\t%q: %q,\n", ak, strings.TrimSpace(av))
		}
		fmt.Println("\t\t},")

		fmt.Println("\t},")
	}

	fmt.Println("}")
}
